---
# Install NFS packages
- name: Install NFS packages
  dnf:
    name: "{{ packages_to_use_nfs }}"
    state: present
  become: yes

# Enable and start the NFS service
- name: Enable and start the NFS service
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no
  become: yes

# Create directory /srv/nfs to export bf NFS
- name: Create directory /srv/nfs to export bf NFS
  file:
    path: /srv/nfs
    state: directory
  become: yes

# Copy and exports file
- name: "Copy and exports file"
  become: true
  copy:
    src: files/exports
    dest: /etc/exports
    mode: u=rw,g=r,o=r

# Reread the /etc/exports file
- name: Run exportfs -r
  command: "exportfs -r"
  become: yes

- name: Run exportfs -s
  command: "exportfs -s"
  become: yes

# Open firewall port to nfs service
- name: Open firewall port to nfs service
  firewalld:
    service: nfs
    permanent: true
    state: enabled
  become: yes

# Open firewall port to rpc-bind service
- name: Open firewall port to rpc-bind service
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled
  become: yes

# Open firewall port to mountd service
- name: Open firewall port to mountd service
  firewalld:
    service: mountd
    permanent: true
    state: enabled
  become: yes

# Reaload firewall
- name: Reaload firewall
  systemd:
    name: firewalld
    state: restarted
  become: yes